#!/usr/bin/env python3
# ═══════════════════════════════════════════════════════════════════════════
#  fiber_decollide.py  —  write resolved collisions back to a derived stage
#
#  fiber_collision.py already DECOMPOSES a collision into two template
#  components (k1,a1,tau1),(k2,a2,tau2) by matching pursuit in the whitened
#  stderiv feature space.  This module turns that decomposition into DATA: for
#  each selected collision it writes the two mutually-subtracted spikes -- each
#  cell's waveform with the OTHER cell removed -- into a new ".decollided" stage,
#  so one merged detection becomes two clean, correctly-timed spikes.
#
#  WHY RAW SPACE FOR THE SUBTRACTION.  The decomposition runs in the stderiv +
#  whitened space (linear, well-conditioned).  Because stderiv and the whitener
#  are linear, the fitted amplitudes a1,a2 are the SAME scalars in raw voltage,
#  so the collision in raw space is  c = a1*T1_raw(tau1) + a2*T2_raw(tau2) + noise
#  and the mutual subtraction is done on the RAW .spk.standard waveform -- the
#  one that preserves amplitudes for localization (the stderiv transform breaks
#  the amplitude-distance law, so cleaned waveforms must live in raw space).
#
#  STAGE, NOT UNDO.  The result is written as a derived stage through the
#  method-pinned writers/readers (res keeps its detection method, everything
#  moves to the shared `tag`); the parent stage is never touched, so the
#  original collision waveforms remain the source of truth and the operation is
#  reversible by construction.  A .decollide.tsv manifest records every resolved
#  collision (source spike, the two output times, k/a/tau for each component,
#  gain) for audit and exact reversal.
#
#  SCOPE.  This writes res + spk.standard + clu for the new stage.  The stderiv
#  .spk and the .fet are REGENERATED by the normal extract/realign step pointed
#  at the .decollided stage (same as the rest of the pipeline) -- de-collision is
#  a detection-level edit; feature extraction follows it.
# ═══════════════════════════════════════════════════════════════════════════
import numpy as np

try:
    from . import neuro_io as nio
except ImportError:
    import neuro_io as nio

MANIFEST_COLS = ["source_idx", "det_time", "k1", "a1", "tau1",
                 "k2", "a2", "tau2", "gain", "time1", "time2"]


def _roll0(w, s):
    """Shift a (nsamp, nch) window by s samples along time, zero-filling the
    vacated edge (NOT circular -- a wrapped spike tail is not real signal)."""
    if s == 0:
        return w
    out = np.zeros_like(w)
    if s > 0:
        out[s:] = w[:-s]
    else:
        out[:s] = w[-s:]
    return out


def decollide_spikes(raw_waves, res_times, clu_ids, sel, decomp, raw_templates):
    """Resolve the collisions at indices `sel` into two spikes each.

    @param raw_waves   (N, nsamp, nch) RAW .spk.standard waveforms (float ok).
    @param res_times   (N,) int spike sample times.
    @param clu_ids     (N,) int cluster ids.
    @param sel         indices (into the arrays above) of the collisions to resolve.
    @param decomp      dict of length-len(sel) arrays k1,a1,tau1,k2,a2,tau2,gain
                       -- exactly fiber_collision.decompose_batch's output, in
                       sel order.  k1/k2 are cluster ids present in raw_templates.
    @param raw_templates {k: (nsamp, nch)} RAW mean template per cluster.

    @return (new_times, new_clu, new_waves, manifest):
       every UNSELECTED spike unchanged, each selected spike REPLACED by two --
       cell k1 at det+tau1 with k2 subtracted, cell k2 recentred at det+tau2 with
       k1 subtracted -- the whole set sorted by time.  manifest is a list of
       dicts (MANIFEST_COLS) in resolution order.
    """
    raw_waves = np.asarray(raw_waves, dtype=np.float64)
    res_times = np.asarray(res_times, dtype=np.int64)
    clu_ids = np.asarray(clu_ids, dtype=np.int64)
    sel = np.asarray(sel, dtype=np.int64)
    selset = {int(i) for i in sel}

    out_t, out_c, out_w, manifest = [], [], [], []

    # unchanged spikes
    for i in range(len(res_times)):
        if int(i) in selset:
            continue
        out_t.append(int(res_times[i])); out_c.append(int(clu_ids[i]))
        out_w.append(raw_waves[i])

    # resolved collisions
    for j, i in enumerate(sel):
        k1 = int(decomp["k1"][j]); a1 = float(decomp["a1"][j]); t1 = int(decomp["tau1"][j])
        k2 = int(decomp["k2"][j]); a2 = float(decomp["a2"][j]); t2 = int(decomp["tau2"][j])
        if k1 not in raw_templates or k2 not in raw_templates:
            # cannot subtract without both templates: leave the spike as-is
            out_t.append(int(res_times[i])); out_c.append(int(clu_ids[i]))
            out_w.append(raw_waves[i]); continue
        T1 = np.asarray(raw_templates[k1], float); T2 = np.asarray(raw_templates[k2], float)
        c = raw_waves[i]
        clean1 = c - a2 * _roll0(T2, t2)            # cell k1 (reference frame, centred)
        clean2 = _roll0(c - a1 * _roll0(T1, t1), -t2)  # cell k2, recentred on its own peak
        det = int(res_times[i])
        out_t.append(det + t1); out_c.append(k1); out_w.append(clean1)
        out_t.append(det + t2); out_c.append(k2); out_w.append(clean2)
        manifest.append(dict(source_idx=int(i), det_time=det, k1=k1, a1=a1, tau1=t1,
                             k2=k2, a2=a2, tau2=t2, gain=float(decomp["gain"][j]),
                             time1=det + t1, time2=det + t2))

    order = np.argsort(np.asarray(out_t, dtype=np.int64), kind="stable")
    new_t = np.asarray(out_t, dtype=np.int64)[order]
    new_c = np.asarray(out_c, dtype=np.int64)[order]
    new_w = np.rint(np.asarray(out_w)[order]).astype(nio.SPK_DTYPE)
    return new_t, new_c, new_w, manifest


def write_manifest(path, manifest):
    """Write the .decollide.tsv provenance sidecar (one row per resolved
    collision).  Mirrors fiber_provenance's .merge.tsv style."""
    with open(path, "w") as f:
        f.write("\t".join(MANIFEST_COLS) + "\n")
        for r in manifest:
            f.write("\t".join(_fmt(r[c]) for c in MANIFEST_COLS) + "\n")
    return path


def read_manifest(path):
    """Read a .decollide.tsv back into a list of dicts (numeric fields typed)."""
    out = []
    with open(path) as f:
        cols = f.readline().rstrip("\n").split("\t")
        for line in f:
            vals = line.rstrip("\n").split("\t")
            row = {}
            for c, v in zip(cols, vals):
                row[c] = int(v) if c in ("source_idx", "det_time", "k1", "tau1",
                                         "k2", "tau2", "time1", "time2") else float(v)
            out.append(row)
    return out


def _fmt(v):
    return f"{v:.6g}" if isinstance(v, float) else str(int(v))


def write_decollided_stage(base, elec, new_times, new_clu, new_waves, manifest, *,
                           tag, res_variant="", clu_variant="", spk_variant="standard",
                           n_clusters=None):
    """Write the derived .decollided stage: res (on its detection variant), clu
    (on its feature variant), spk.standard (raw cleaned waveforms) -- all at the
    shared `tag` -- plus the .decollide.tsv manifest.  Each file keeps its own
    variant; only the tag is shared (the staging rule).  Returns the paths dict.

    The stderiv .spk and .fet are NOT written here -- regenerate them by running
    the normal extract/realign step against this stage (de-collision is a
    detection-level edit)."""
    paths = {}
    paths["res"] = nio.write_res(base, elec, new_times, variant=res_variant, tag=tag)
    paths["clu"] = nio.write_clu(base, elec, new_clu, n_clusters=n_clusters,
                                 variant=clu_variant, tag=tag)
    paths["spk"] = nio.write_spk(base, elec, new_waves, variant=spk_variant, tag=tag)
    man = nio.session_path(base, "decollide", elec, variant=clu_variant, tag=tag) + ".tsv"
    paths["manifest"] = write_manifest(man, manifest)
    return paths


def reconstruct_collision(manifest_row, raw_templates, nsamp, nch):
    """The audit inverse: a1*T1(tau1) + a2*T2(tau2) -- the template-model
    reconstruction of a resolved collision, for checking the fit (the EXACT
    original stays in the untouched parent stage at source_idx)."""
    r = manifest_row
    w = np.zeros((nsamp, nch), float)
    w += r["a1"] * _roll0(np.asarray(raw_templates[r["k1"]], float), r["tau1"])
    w += r["a2"] * _roll0(np.asarray(raw_templates[r["k2"]], float), r["tau2"])
    return w


# ── orchestration / CLI ──────────────────────────────────────────────────────
# The DECOMPOSITION (which cells, lags, amplitudes) is fiber_collision's job and
# needs the per-chunk .fil whitener (fiber_lib), so it runs where the filtered
# signal lives -- the lab machine, or the Klusters resolve action which already
# has the data loaded.  That producer writes a small decomposition spec; this
# consumer turns it into the .decollided stage.  The split keeps the whitener out
# of this module and makes the stage-writing half deterministic and testable.
#
# Decomposition spec (an .npz): `sel` (int, the spike indices resolved) plus the
# length-|sel| arrays k1,a1,tau1,k2,a2,tau2,gain -- exactly
# fiber_collision.decompose_batch's output, sliced to the confident collisions.

DECOMP_KEYS = ("k1", "a1", "tau1", "k2", "a2", "tau2", "gain")


def decollide_from_decomposition(base, elec, *, nsamp, nch, sel, decomp, tag,
                                 clu_variant, res_variant="stderiv",
                                 spk_variant="standard", parent_tag="", min_tmpl=40):
    """Write the .decollided stage from a decomposition produced elsewhere.
    Loads the parent res/clu + RAW .spk through the method-pinned readers -- the
    parent's res and clu carry DIFFERENT variants (detection vs feature), which a
    single resolve cannot name -- builds the raw per-cluster templates, resolves
    `sel`, and writes the staged res/clu/spk + manifest.  Deterministic from
    (`sel`, `decomp`); the whitener-dependent step that made them is the caller's.
    @param parent_tag  stage of the PARENT being de-collided ('' = the base files;
                       e.g. 'tsne_chunk' to de-collide a curated stage)."""
    res_times = nio.read_res_at(base, elec, variant=res_variant, tag=parent_tag)
    _, clu_ids = nio.read_clu_at(base, elec, variant=clu_variant, tag=parent_tag,
                                 n_spikes=res_times.size)
    if clu_ids.size != res_times.size:
        raise RuntimeError("parent res/clu length mismatch")
    raw = np.asarray(nio.open_spk_at(base, elec, nsamp, nch,
                                     variant=spk_variant, tag=parent_tag), float)
    raw_T = {int(k): raw[clu_ids == k].mean(0)
             for k in np.unique(clu_ids[clu_ids >= 0])
             if np.count_nonzero(clu_ids == k) >= min_tmpl}
    nt, nc, nw, manifest = decollide_spikes(raw, res_times, clu_ids, sel, decomp, raw_T)
    return write_decollided_stage(base, elec, nt, nc, nw, manifest, tag=tag,
                                  res_variant=res_variant, clu_variant=clu_variant,
                                  spk_variant=spk_variant)


def main():
    import argparse
    ap = argparse.ArgumentParser(
        description="Write a derived .decollided stage (two mutually-subtracted "
                    "spikes per collision) from a fiber_collision decomposition spec.")
    ap.add_argument("base"); ap.add_argument("elec", type=int)
    ap.add_argument("--clu-method", required=True, help="feature variant of the .clu (e.g. stderiv_C5_D34)")
    ap.add_argument("--res-method", default="stderiv", help="detection variant of the .res (default stderiv)")
    ap.add_argument("--spk-variant", default="standard", help="raw .spk variant to subtract in (default standard)")
    ap.add_argument("--tag", default="decollided", help="shared stage tag for the derived files")
    ap.add_argument("--parent-tag", default="", help="stage of the parent being de-collided ('' = base files)")
    ap.add_argument("--nsamp", type=int, required=True)
    ap.add_argument("--nch", type=int, required=True)
    ap.add_argument("--decomp", required=True,
                    help="npz with 'sel' + k1,a1,tau1,k2,a2,tau2,gain (fiber_collision output)")
    a = ap.parse_args()
    z = np.load(a.decomp)
    sel = np.asarray(z["sel"], np.int64)
    decomp = {k: np.asarray(z[k]) for k in DECOMP_KEYS}
    paths = decollide_from_decomposition(
        a.base, a.elec, nsamp=a.nsamp, nch=a.nch, sel=sel, decomp=decomp, tag=a.tag,
        clu_variant=a.clu_method, res_variant=a.res_method, spk_variant=a.spk_variant,
        parent_tag=a.parent_tag)
    for k, v in paths.items():
        print(f"[decollide] {k}: {v}")


if __name__ == "__main__":
    main()
