#!/usr/bin/env python3
# ═══════════════════════════════════════════════════════════════════════════
#  fiber_decollide.py  —  write resolved collisions back to a derived stage
#
#  fiber_collision.py already DECOMPOSES a collision into two template
#  components (k1,a1,tau1),(k2,a2,tau2) by matching pursuit in the whitened
#  stderiv feature space.  This module turns that decomposition into DATA: for
#  each selected collision it writes the two mutually-subtracted spikes -- each
#  cell's waveform with the OTHER cell removed -- into a new ".decollided" stage,
#  so one merged detection becomes two clean, correctly-timed spikes.
#
#  WHY RAW SPACE FOR THE SUBTRACTION.  The decomposition runs in the stderiv +
#  whitened space (linear, well-conditioned).  Because stderiv and the whitener
#  are linear, the fitted amplitudes a1,a2 are the SAME scalars in raw voltage,
#  so the collision in raw space is  c = a1*T1_raw(tau1) + a2*T2_raw(tau2) + noise
#  and the mutual subtraction is done on the RAW .spk.standard waveform -- the
#  one that preserves amplitudes for localization (the stderiv transform breaks
#  the amplitude-distance law, so cleaned waveforms must live in raw space).
#
#  STAGE, NOT UNDO.  The result is written as a derived stage through the
#  method-pinned writers/readers (res keeps its detection method, everything
#  moves to the shared `tag`); the parent stage is never touched, so the
#  original collision waveforms remain the source of truth and the operation is
#  reversible by construction.  A .decollide.tsv manifest records every resolved
#  collision (source spike, the two output times, k/a/tau for each component,
#  gain) for audit and exact reversal.
#
#  SCOPE.  This writes res + spk.standard + clu for the new stage.  The stderiv
#  .spk and the .fet are REGENERATED by the normal extract/realign step pointed
#  at the .decollided stage (same as the rest of the pipeline) -- de-collision is
#  a detection-level edit; feature extraction follows it.
# ═══════════════════════════════════════════════════════════════════════════
import os

import numpy as np

try:
    from . import neuro_io as nio
except ImportError:
    import neuro_io as nio

MANIFEST_COLS = ["source_idx", "det_time", "k1", "a1", "tau1",
                 "k2", "a2", "tau2", "gain", "time1", "time2"]


def _roll0(w, s):
    """Shift a (nsamp, nch) window by s samples along time, zero-filling the
    vacated edge (NOT circular -- a wrapped spike tail is not real signal)."""
    if s == 0:
        return w
    out = np.zeros_like(w)
    if s > 0:
        out[s:] = w[:-s]
    else:
        out[:s] = w[-s:]
    return out


def decollide_spikes(raw_waves, res_times, clu_ids, sel, decomp, raw_templates):
    """Resolve the collisions at indices `sel` into two spikes each.

    @param raw_waves   (N, nsamp, nch) RAW .spk.standard waveforms (float ok).
    @param res_times   (N,) int spike sample times.
    @param clu_ids     (N,) int cluster ids.
    @param sel         indices (into the arrays above) of the collisions to resolve.
    @param decomp      dict of length-len(sel) arrays k1,a1,tau1,k2,a2,tau2,gain
                       -- exactly fiber_collision.decompose_batch's output, in
                       sel order.  k1/k2 are cluster ids present in raw_templates.
    @param raw_templates {k: (nsamp, nch)} RAW mean template per cluster.

    @return (new_times, new_clu, new_waves, manifest):
       every UNSELECTED spike unchanged, each selected spike REPLACED by two --
       cell k1 at det+tau1 with k2 subtracted, cell k2 recentred at det+tau2 with
       k1 subtracted -- the whole set sorted by time.  manifest is a list of
       dicts (MANIFEST_COLS) in resolution order.
    """
    raw_waves = np.asarray(raw_waves, dtype=np.float64)
    res_times = np.asarray(res_times, dtype=np.int64)
    clu_ids = np.asarray(clu_ids, dtype=np.int64)
    sel = np.asarray(sel, dtype=np.int64)
    selset = {int(i) for i in sel}

    out_t, out_c, out_w, manifest = [], [], [], []

    # unchanged spikes
    for i in range(len(res_times)):
        if int(i) in selset:
            continue
        out_t.append(int(res_times[i])); out_c.append(int(clu_ids[i]))
        out_w.append(raw_waves[i])

    # resolved collisions
    for j, i in enumerate(sel):
        k1 = int(decomp["k1"][j]); a1 = float(decomp["a1"][j]); t1 = int(decomp["tau1"][j])
        k2 = int(decomp["k2"][j]); a2 = float(decomp["a2"][j]); t2 = int(decomp["tau2"][j])
        if k1 not in raw_templates or k2 not in raw_templates:
            # cannot subtract without both templates: leave the spike as-is
            out_t.append(int(res_times[i])); out_c.append(int(clu_ids[i]))
            out_w.append(raw_waves[i]); continue
        T1 = np.asarray(raw_templates[k1], float); T2 = np.asarray(raw_templates[k2], float)
        c = raw_waves[i]
        clean1 = c - a2 * _roll0(T2, t2)            # cell k1 (reference frame, centred)
        clean2 = _roll0(c - a1 * _roll0(T1, t1), -t2)  # cell k2, recentred on its own peak
        det = int(res_times[i])
        out_t.append(det + t1); out_c.append(k1); out_w.append(clean1)
        out_t.append(det + t2); out_c.append(k2); out_w.append(clean2)
        manifest.append(dict(source_idx=int(i), det_time=det, k1=k1, a1=a1, tau1=t1,
                             k2=k2, a2=a2, tau2=t2, gain=float(decomp["gain"][j]),
                             time1=det + t1, time2=det + t2))

    order = np.argsort(np.asarray(out_t, dtype=np.int64), kind="stable")
    new_t = np.asarray(out_t, dtype=np.int64)[order]
    new_c = np.asarray(out_c, dtype=np.int64)[order]
    new_w = np.rint(np.asarray(out_w)[order]).astype(nio.SPK_DTYPE)
    return new_t, new_c, new_w, manifest


def write_manifest(path, manifest):
    """Write the .decollide.tsv provenance sidecar (one row per resolved
    collision).  Mirrors fiber_provenance's .merge.tsv style."""
    with open(path, "w") as f:
        f.write("\t".join(MANIFEST_COLS) + "\n")
        for r in manifest:
            f.write("\t".join(_fmt(r[c]) for c in MANIFEST_COLS) + "\n")
    return path


def read_manifest(path):
    """Read a .decollide.tsv back into a list of dicts (numeric fields typed)."""
    out = []
    with open(path) as f:
        cols = f.readline().rstrip("\n").split("\t")
        for line in f:
            vals = line.rstrip("\n").split("\t")
            row = {}
            for c, v in zip(cols, vals):
                row[c] = int(v) if c in ("source_idx", "det_time", "k1", "tau1",
                                         "k2", "tau2", "time1", "time2") else float(v)
            out.append(row)
    return out


def _fmt(v):
    return f"{v:.6g}" if isinstance(v, float) else str(int(v))


def write_decollided_stage(base, elec, new_times, new_clu, new_waves, manifest, *,
                           tag, res_variant="", clu_variant="", spk_variant="standard",
                           n_clusters=None):
    """Write the derived .decollided stage: res (on its detection variant), clu
    (on its feature variant), spk.standard (raw cleaned waveforms) -- all at the
    shared `tag` -- plus the .decollide.tsv manifest.  Each file keeps its own
    variant; only the tag is shared (the staging rule).  Returns the paths dict.

    Writes ONE spk variant and no .fet; for new units in EVERY variant's .spk +
    .fet (the linear-subtraction-per-variant path), use decollide_all_variants."""
    paths = {}
    paths["res"] = nio.write_res(base, elec, new_times, variant=res_variant, tag=tag)
    paths["clu"] = nio.write_clu(base, elec, new_clu, n_clusters=n_clusters,
                                 variant=clu_variant, tag=tag)
    paths["spk"] = nio.write_spk(base, elec, new_waves, variant=spk_variant, tag=tag)
    man = nio.session_path(base, "decollide", elec, variant=clu_variant, tag=tag) + ".tsv"
    paths["manifest"] = write_manifest(man, manifest)
    return paths


def reconstruct_collision(manifest_row, raw_templates, nsamp, nch):
    """The audit inverse: a1*T1(tau1) + a2*T2(tau2) -- the template-model
    reconstruction of a resolved collision, for checking the fit (the EXACT
    original stays in the untouched parent stage at source_idx)."""
    r = manifest_row
    w = np.zeros((nsamp, nch), float)
    w += r["a1"] * _roll0(np.asarray(raw_templates[r["k1"]], float), r["tau1"])
    w += r["a2"] * _roll0(np.asarray(raw_templates[r["k2"]], float), r["tau2"])
    return w


# ── orchestration / CLI ──────────────────────────────────────────────────────
# The DECOMPOSITION (which cells, lags, amplitudes) is fiber_collision's job and
# needs the per-chunk .fil whitener (fiber_lib), so it runs where the filtered
# signal lives -- the lab machine, or the Klusters resolve action which already
# has the data loaded.  That producer writes a small decomposition spec; this
# consumer turns it into the .decollided stage.  The split keeps the whitener out
# of this module and makes the stage-writing half deterministic and testable.
#
# Decomposition spec (an .npz): `sel` (int, the spike indices resolved) plus the
# length-|sel| arrays k1,a1,tau1,k2,a2,tau2,gain -- exactly
# fiber_collision.decompose_batch's output, sliced to the confident collisions.

DECOMP_KEYS = ("k1", "a1", "tau1", "k2", "a2", "tau2", "gain")


# ── .eap membership (annotate-in-place) ──────────────────────────────────────
# The .decollided stage above is the GROW/export representation (each collision
# split into two physical spikes).  The .eap is the ALTERNATIVE annotate-in-place
# representation the EAP model wants: it marks, on the PARENT stage's own spike
# rows, which template classes each collision waveform contains and at what integer
# offset -- without growing rows.  For each manifest row: eap[source_idx][col(k)] =
# clamp(tau) for both constituents, mapping each unit k to a STABLE .tcl class
# (reused by provenance, else allocated; pool grown on exhaustion).  Mirrors the
# C++ neurosuite::decollide::applyDecompsToEap + process_decomposecollisions'
# writer, so a .eap written here reads identically through neurofileio.  Amplitude
# / fractional shift stay in the .decollide manifest; .eap is presence + int offset.

def _eap_class_for_unit(entries, unit):
    """Lowest-col active class whose provenance_clu == unit, or -1 (the reuse rule)."""
    found = -1
    for e in entries:
        if e.get("status") == "active" and int(e.get("provenance_clu", -1)) == int(unit):
            c = int(e.get("col", 0))
            if found < 0 or c < found:
                found = c
    return found


def _eap_clamp(tau):
    """Clamp an int sample shift into int8, never the ABSENT sentinel (-128)."""
    tau = int(tau)
    if tau > 127:
        tau = 127
    if tau < -127:
        tau = -127                    # -128 == EAP_ABSENT, never a real offset
    return tau


def _blank_tcl_entry(col):
    return dict(col=int(col), status="free", label="", provenance_clu=-1,
                provenance_stage="", created="", merged_into=-1)


def write_eap_membership(base, elec, *, parent_tag, n_spikes, manifest,
                         n_cells=128, created=None):
    """Record the decollide `manifest` as .eap membership (+ .tcl classes) on the
    PARENT stage (`parent_tag`).  Resolution: the parent stage's .eap; else a fresh
    all-absent N × n_cells (process_initeap normally pre-builds it).  Each unit maps
    to a stable .tcl class column (reuse by provenance, else allocate; grow when the
    free pool is exhausted).  Returns {'eap':…, 'tcl':…, 'cells':N_written} or None
    (nothing to write / an N mismatch that would corrupt the matrix)."""
    if not manifest:
        return None
    if created is None:
        import datetime
        created = datetime.date.today().isoformat()
    grow_by = int(n_cells) if (n_cells and int(n_cells) > 0) else 128

    cur = nio.read_eap(base, elec, tag=parent_tag)
    if cur["ok"]:
        cells = np.array(cur["cells"], dtype=np.int8, copy=True)
        N = int(cur["nSpikes"])
    else:
        N = int(n_spikes)
        cells = np.full((N, grow_by), nio.EAP_ABSENT, dtype=np.int8)
    if N != int(n_spikes):
        return None                   # parent spike count disagrees -> refuse

    reg = nio.read_tcl(base, elec)
    entries = (reg["entries"] if reg["ok"]
               else [_blank_tcl_entry(i) for i in range(cells.shape[1])])

    # Reconcile widths: a class column must be valid in BOTH structures (a sibling
    # stage may have grown the shared .tcl pool).
    T = max(cells.shape[1], len(entries))
    if cells.shape[1] < T:
        cells = np.concatenate(
            [cells, np.full((cells.shape[0], T - cells.shape[1]), nio.EAP_ABSENT, np.int8)], axis=1)
    while len(entries) < T:
        entries.append(_blank_tcl_entry(len(entries)))

    def first_free():
        for e in entries:
            if e.get("status") == "free":
                return int(e["col"])
        return -1

    def grow():
        nonlocal cells
        newT = cells.shape[1] + grow_by
        cells = np.concatenate(
            [cells, np.full((cells.shape[0], newT - cells.shape[1]), nio.EAP_ABSENT, np.int8)], axis=1)
        while len(entries) < newT:
            entries.append(_blank_tcl_entry(len(entries)))

    def col_for_unit(unit):
        c = _eap_class_for_unit(entries, unit)
        if c >= 0:
            return c
        c = first_free()
        if c < 0:
            grow()
            c = first_free()
        e = entries[c]
        e.update(status="active", provenance_clu=int(unit),
                 provenance_stage=(parent_tag or ""), created=created, merged_into=-1)
        return c

    written = 0
    for r in manifest:
        i = int(r["source_idx"])
        if i < 0 or i >= N:
            continue
        for uk, tk in ((int(r["k1"]), int(r["tau1"])), (int(r["k2"]), int(r["tau2"]))):
            col = col_for_unit(uk)          # may grow() + rebind `cells`; resolve BEFORE
            cells[i, col] = _eap_clamp(tk)  # indexing, so the store targets the grown array
            written += 1

    eap_path = nio.write_eap(base, elec, cells, group=int(elec), tag=(parent_tag or ""))
    tcl_path = nio.write_tcl(base, elec, entries, n_classes=cells.shape[1])
    return dict(eap=eap_path, tcl=tcl_path, cells=written)


def decollide_from_decomposition(base, elec, *, nsamp, nch, sel, decomp, tag,
                                 clu_variant, res_variant="stderiv",
                                 spk_variant="standard", parent_tag="", min_tmpl=40,
                                 eap=True, n_cells=128):
    """Write the .decollided stage from a decomposition produced elsewhere.
    Loads the parent res/clu + RAW .spk through the method-pinned readers -- the
    parent's res and clu carry DIFFERENT variants (detection vs feature), which a
    single resolve cannot name -- builds the raw per-cluster templates, resolves
    `sel`, and writes the staged res/clu/spk + manifest.  Deterministic from
    (`sel`, `decomp`); the whitener-dependent step that made them is the caller's.
    @param parent_tag  stage of the PARENT being de-collided ('' = the base files;
                       e.g. 'tsne_chunk' to de-collide a curated stage)."""
    res_times = nio.read_res_at(base, elec, variant=res_variant, tag=parent_tag)
    _, clu_ids = nio.read_clu_at(base, elec, variant=clu_variant, tag=parent_tag,
                                 n_spikes=res_times.size)
    if clu_ids.size != res_times.size:
        raise RuntimeError("parent res/clu length mismatch")
    raw = np.asarray(nio.open_spk_at(base, elec, nsamp, nch,
                                     variant=spk_variant, tag=parent_tag), float)
    raw_T = {int(k): raw[clu_ids == k].mean(0)
             for k in np.unique(clu_ids[clu_ids >= 0])
             if np.count_nonzero(clu_ids == k) >= min_tmpl}
    nt, nc, nw, manifest = decollide_spikes(raw, res_times, clu_ids, sel, decomp, raw_T)
    paths = write_decollided_stage(base, elec, nt, nc, nw, manifest, tag=tag,
                                   res_variant=res_variant, clu_variant=clu_variant,
                                   spk_variant=spk_variant)
    if eap:
        em = write_eap_membership(base, elec, parent_tag=parent_tag,
                                  n_spikes=int(res_times.size), manifest=manifest,
                                  n_cells=n_cells)
        if em:
            paths["eap"] = em["eap"]
            paths["tcl"] = em["tcl"]
    return paths


# ── new units in EVERY variant (.spk + .fet) ─────────────────────────────────
# A de-collided constituent is a NEW spike: its waveform is the recovered
# (mutually-subtracted) one, which cannot be re-extracted from the .dat (the .dat
# holds the collision SUM).  But the subtraction is LINEAR, so running it in a
# given variant's .spk space -- that variant's collision window minus that
# variant's scaled, shifted partner template -- yields the constituent's waveform
# in that variant.  So the stage carries new units' .spk AND .fet in every
# method: run the SAME decomposition once per variant, then featurise each with
# that variant's PCA basis.  res/clu/manifest are shared (one physical spike set).

def _variant_templates(base, elec, nsamp, nch, clu_ids, variant, parent_tag, min_tmpl):
    """(waves, {k: mean template}) in `variant`'s .spk space, for the subtraction."""
    w = np.asarray(nio.open_spk_at(base, elec, nsamp, nch, variant=variant, tag=parent_tag), float)
    if w.shape[0] != clu_ids.size:
        raise RuntimeError(f"{variant} .spk length {w.shape[0]} != clu {clu_ids.size}")
    T = {int(k): w[clu_ids == k].mean(0)
         for k in np.unique(clu_ids[clu_ids >= 0])
         if np.count_nonzero(clu_ids == k) >= min_tmpl}
    return w, T


def write_variant_spk_fet(base, elec, waves, *, variant, tag, write_fet=True, realign=True):
    """Write the stage's .spk for `variant`, and -- when a PCA basis for that
    variant exists (<base>.pca.<variant>.<elec>) -- its .fet, projecting the
    waveforms onto that basis (fiber_pca.cluster_features).  Returns {'spk':…[,
    'fet':…]}; .fet is skipped (no error) when no basis exists."""
    out = {"spk": nio.write_spk(base, elec, waves, variant=variant, tag=tag)}
    if not write_fet:
        return out
    pca_path = nio.session_path(base, "pca", elec, variant=variant)
    if not os.path.exists(pca_path):
        return out
    try:
        from . import fiber_pca as fp
    except ImportError:
        import fiber_pca as fp
    basis = fp.read_pcad(pca_path)
    feats = fp.cluster_features(np.asarray(waves, np.float32), basis, realign=realign)
    if feats is not None:
        out["fet"] = nio.write_fet(base, elec, feats, variant=variant, tag=tag)
    return out


def decollide_all_variants(base, elec, *, nsamp, nch, sel, decomp, tag, clu_variant,
                           res_variant="stderiv", spk_variants=("standard",),
                           parent_tag="", min_tmpl=40, write_fet=True, realign=True,
                           eap=True, n_cells=128):
    """De-collide and write the stage with new units' .spk AND .fet in EVERY
    variant in @p spk_variants.  The mutual subtraction is run once per variant
    (that variant's .spk + templates, the SAME decomposition), so each new
    constituent gets its waveform in every method's space; res (detection variant),
    clu (feature variant) and the manifest are shared.  Returns the paths dict:
    'res','clu','manifest' plus 'spk.<variant>' / 'fet.<variant>' per variant."""
    res_times = nio.read_res_at(base, elec, variant=res_variant, tag=parent_tag)
    _, clu_ids = nio.read_clu_at(base, elec, variant=clu_variant, tag=parent_tag,
                                 n_spikes=res_times.size)
    if clu_ids.size != res_times.size:
        raise RuntimeError("parent res/clu length mismatch")

    paths = {}
    nt = nc = manifest = None
    for v in spk_variants:
        w, T = _variant_templates(base, elec, nsamp, nch, clu_ids, v, parent_tag, min_tmpl)
        vt, vc, vw, vman = decollide_spikes(w, res_times, clu_ids, sel, decomp, T)
        if nt is None:                       # identical across variants (shared decomposition)
            nt, nc, manifest = vt, vc, vman
        for k, p in write_variant_spk_fet(base, elec, vw, variant=v, tag=tag,
                                          write_fet=write_fet, realign=realign).items():
            paths[f"{k}.{v}"] = p

    paths["res"] = nio.write_res(base, elec, nt, variant=res_variant, tag=tag)
    paths["clu"] = nio.write_clu(base, elec, nc, variant=clu_variant, tag=tag)
    man = nio.session_path(base, "decollide", elec, variant=clu_variant, tag=tag) + ".tsv"
    paths["manifest"] = write_manifest(man, manifest)
    if eap:
        em = write_eap_membership(base, elec, parent_tag=parent_tag,
                                  n_spikes=int(res_times.size), manifest=manifest,
                                  n_cells=n_cells)
        if em:
            paths["eap"] = em["eap"]
            paths["tcl"] = em["tcl"]
    return paths


def main():
    import argparse
    ap = argparse.ArgumentParser(
        description="Write a derived .decollided stage (two mutually-subtracted "
                    "spikes per collision) from a fiber_collision decomposition spec.")
    ap.add_argument("base"); ap.add_argument("elec", type=int)
    ap.add_argument("--clu-method", required=True, help="feature variant of the .clu (e.g. stderiv_C5_D34)")
    ap.add_argument("--res-method", default="stderiv", help="detection variant of the .res (default stderiv)")
    ap.add_argument("--spk-variant", default="standard", help="raw .spk variant to subtract in (default standard)")
    ap.add_argument("--spk-variants", nargs="+", default=None,
                    help="write new units' .spk + .fet in EVERY listed variant "
                         "(e.g. standard stderiv_C5_D34) via decollide_all_variants")
    ap.add_argument("--no-fet", action="store_true", help="with --spk-variants, skip the .fet projection")
    ap.add_argument("--tag", default="decollided", help="shared stage tag for the derived files")
    ap.add_argument("--parent-tag", default="", help="stage of the parent being de-collided ('' = base files)")
    ap.add_argument("--no-eap", action="store_true",
                    help="skip writing the .eap membership (+ .tcl) on the parent stage")
    ap.add_argument("--n-cells", type=int, default=128,
                    help="template-class columns (T) when a fresh .eap must be built (default 128)")
    ap.add_argument("--nsamp", type=int, required=True)
    ap.add_argument("--nch", type=int, required=True)
    ap.add_argument("--decomp", required=True,
                    help="npz with 'sel' + k1,a1,tau1,k2,a2,tau2,gain (fiber_collision output)")
    a = ap.parse_args()
    z = np.load(a.decomp)
    sel = np.asarray(z["sel"], np.int64)
    decomp = {k: np.asarray(z[k]) for k in DECOMP_KEYS}
    if a.spk_variants:
        paths = decollide_all_variants(
            a.base, a.elec, nsamp=a.nsamp, nch=a.nch, sel=sel, decomp=decomp, tag=a.tag,
            clu_variant=a.clu_method, res_variant=a.res_method,
            spk_variants=tuple(a.spk_variants), parent_tag=a.parent_tag, write_fet=not a.no_fet,
            eap=not a.no_eap, n_cells=a.n_cells)
    else:
        paths = decollide_from_decomposition(
            a.base, a.elec, nsamp=a.nsamp, nch=a.nch, sel=sel, decomp=decomp, tag=a.tag,
            clu_variant=a.clu_method, res_variant=a.res_method, spk_variant=a.spk_variant,
            parent_tag=a.parent_tag, eap=not a.no_eap, n_cells=a.n_cells)
    for k, v in paths.items():
        print(f"[decollide] {k}: {v}")


if __name__ == "__main__":
    main()
